### PR TITLE
task/1449

### PR DESCRIPTION
**Pull request by brouillette**

### CODE REVIEW

**Review by gsfk — COMMENTED** [review]
Okay, thanks, I think it's better without the long crufty filenames (like this one: `HG00146-15a4aa221f16df70fd6cb6e71d5ee04c761db78d.vcf.gz)`

But why were they there in the first place? It seems like... if you do everything in order (and, for me at least, fix a few errors in the script).... that running `sample.vcf.sh` will produce vcfs with the same ugly crufty filenames, but that actually match some of the content of the experiments file. But then things would break if you:
- tried to use this data with other vcfs you had lying around with more coherent filenames, like `HG00146.vcf.gz`
- ran `generate_experiments.py` before running  `sample.vcf.sh`
- didn't run  `sample.vcf.sh` at all
- put your own coherently-named vcfs in `./data` and expected things to work properly

So `sample.vcf.sh` needs some work, although I'm not convinced it's worth keeping. At the very least we need to have consistent filenames. 

There's also some strange behaviour remaining in the experiments generator, it will generate multiple references to the same vcf file in a single experiment, for example.

**Comment by brouillette** [comment]
I cannot comment on `sample.vcf.sh` as I haven't had to use it to this point

**Review by gsfk — APPROVED** [review]
Okay, this seems like it resolves the filename / sample id issues, thanks. Some remaining issues:

- many experiment results entries have duplicate references (like the same vcf being referred to twice, that can really mess stuff up in the interface)
- some stuff is broken in `sample.vcf.sh`, it looks like this was written on a Mac and never tested on Linux. 
 
The second one probably merits a separate pr, not sure about the first.

**Comment by brouillette** [comment]
Duplicate references to VCFs/CRAMs issue fixed with the following:
- randomly decide whether to include a VCF
- in the event that a VCF is included, randomly decide whether or not to also include a CRAM

I would also vouch for addressing the broken `sample.vcf.sh` in a separate ticket

**Pull request merged**
